# Generated by Django 2.1.4 on 2019-01-07 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_student_student_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=100)),
                ('user_phone', models.CharField(max_length=20)),
                ('user_email', models.EmailField(max_length=50)),
                ('user_details', models.CharField(max_length=255)),
            ],
        ),
    ]
