# Generated by Django 2.1.4 on 2019-01-07 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollectResume',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=100)),
                ('user_phone', models.CharField(max_length=20)),
                ('user_email', models.EmailField(max_length=50)),
                ('user_exp', models.CharField(max_length=50)),
                ('user_current_ctc', models.CharField(max_length=50)),
                ('user_resume', models.CharField(max_length=50)),
                ('user_msg', models.CharField(max_length=225)),
            ],
        ),
    ]
