# Generated by Django 2.1.4 on 2019-01-07 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_collectresume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectresume',
            name='user_resume',
            field=models.FileField(max_length=50, upload_to=''),
        ),
    ]
