# Generated by Django 2.1.4 on 2019-01-07 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20190107_1018'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectresume',
            name='current_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
