# Generated by Django 2.1.4 on 2019-01-07 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_collectresume_current_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectresume',
            name='user_msg',
            field=models.TextField(max_length=225),
        ),
    ]
