# Generated by Django 2.1.4 on 2019-01-07 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20190107_1103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectresume',
            name='user_current_ctc',
            field=models.SmallIntegerField(max_length=50),
        ),
        migrations.AlterField(
            model_name='collectresume',
            name='user_exp',
            field=models.SmallIntegerField(max_length=50),
        ),
        migrations.AlterField(
            model_name='collectresume',
            name='user_phone',
            field=models.SmallIntegerField(max_length=20),
        ),
        migrations.AlterField(
            model_name='collectresume',
            name='user_resume',
            field=models.FileField(max_length=50, upload_to='uploads/%Y/%m/%d/'),
        ),
    ]
