# Generated by Django 2.1.4 on 2019-01-07 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20190107_1136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectresume',
            name='user_current_ctc',
            field=models.SmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='collectresume',
            name='user_exp',
            field=models.SmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='collectresume',
            name='user_phone',
            field=models.SmallIntegerField(),
        ),
    ]
