# Generated by Django 2.1.4 on 2019-01-07 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20190107_1137'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobApply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('fathername', models.CharField(max_length=100)),
                ('mothername', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=6)),
                ('high_qual', models.CharField(choices=[('B.E', 'B.E'), ('M.Sc', 'M.Sc')], max_length=6)),
                ('year_of_qual', models.CharField(choices=[(2015, 2015), (2016, 2016), (2017, 2017)], max_length=6)),
                ('marital', models.CharField(choices=[('married', 'married'), ('un-married', 'un-married')], max_length=6)),
                ('act_exp', models.CharField(choices=[('1 year', '1 year'), ('2 year', '2 year'), ('3 year', '3 year')], max_length=6)),
                ('total_exp', models.CharField(choices=[('1 year', '1 year'), ('2 year', '2 year'), ('3 year', '3 year')], max_length=6)),
                ('emailid', models.EmailField(max_length=50)),
                ('contact_no', models.SmallIntegerField()),
                ('alt_contact_no', models.SmallIntegerField()),
                ('employer_name', models.CharField(max_length=50)),
                ('employer_location', models.CharField(max_length=150)),
                ('startdate', models.DateField()),
                ('endtdate', models.DateField()),
                ('skills', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('area', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('pincode', models.SmallIntegerField()),
                ('resume', models.FileField(max_length=50, upload_to='uploads/%Y/%m/%d/')),
            ],
        ),
    ]
