# Generated by Django 2.1.4 on 2019-01-08 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_jobapply'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapply',
            name='endtdate',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='jobapply',
            name='startdate',
            field=models.CharField(max_length=30),
        ),
    ]
