# Generated by Django 2.1.4 on 2019-01-08 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_auto_20190108_0537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapply',
            name='act_exp',
            field=models.CharField(choices=[('1 year', '1 year'), ('2 year', '2 year'), ('3 year', '3 year')], max_length=50),
        ),
        migrations.AlterField(
            model_name='jobapply',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=50),
        ),
        migrations.AlterField(
            model_name='jobapply',
            name='high_qual',
            field=models.CharField(choices=[('B.E', 'B.E'), ('M.Sc', 'M.Sc')], max_length=50),
        ),
        migrations.AlterField(
            model_name='jobapply',
            name='marital',
            field=models.CharField(choices=[('married', 'married'), ('un-married', 'un-married')], max_length=50),
        ),
        migrations.AlterField(
            model_name='jobapply',
            name='total_exp',
            field=models.CharField(choices=[('1 year', '1 year'), ('2 year', '2 year'), ('3 year', '3 year')], max_length=50),
        ),
        migrations.AlterField(
            model_name='jobapply',
            name='year_of_qual',
            field=models.CharField(choices=[(2015, 2015), (2016, 2016), (2017, 2017)], max_length=50),
        ),
    ]
