# Generated by Django 2.1.4 on 2019-01-08 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_auto_20190108_0542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapply',
            name='alt_contact_no',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='jobapply',
            name='contact_no',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='jobapply',
            name='emailid',
            field=models.EmailField(max_length=255),
        ),
        migrations.AlterField(
            model_name='jobapply',
            name='pincode',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='jobapply',
            name='year_of_qual',
            field=models.CharField(choices=[('2015', '2015'), ('2016', '2016'), ('2017', '2017')], max_length=50),
        ),
    ]
