# Generated by Django 2.1.4 on 2019-01-08 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_auto_20190108_0612'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='JobApply',
            new_name='JobApplyTable',
        ),
    ]
