# Generated by Django 2.1.4 on 2019-01-08 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_auto_20190108_0704'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobApplyTables',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('fathername', models.CharField(max_length=100)),
                ('mothername', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=50)),
                ('high_qual', models.CharField(max_length=50)),
                ('year_of_qual', models.CharField(max_length=50)),
                ('marital', models.CharField(max_length=50)),
                ('act_exp', models.CharField(max_length=50)),
                ('total_exp', models.CharField(max_length=50)),
                ('emailid', models.EmailField(max_length=255)),
                ('contact_no', models.CharField(max_length=20)),
                ('alt_contact_no', models.CharField(max_length=20)),
                ('employer_fname', models.CharField(max_length=50)),
                ('employer_lname', models.CharField(max_length=150)),
                ('employer_location', models.CharField(max_length=150)),
                ('startdate', models.CharField(max_length=50)),
                ('endtdate', models.CharField(max_length=50)),
                ('skills', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('area', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('pincode', models.CharField(max_length=100)),
                ('resume', models.FileField(max_length=255, upload_to='uploads/%Y/%m/%d/')),
            ],
        ),
        migrations.DeleteModel(
            name='JobApplyTable',
        ),
    ]
