# Generated by Django 2.1.4 on 2019-01-09 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_auto_20190108_1159'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='JobApplyTables',
            new_name='JobApply',
        ),
    ]
